#!/usr/bin/env python3
"""
Fill native translations for the 11 languages that were on English fallback
for the insider.* section. Also translates the insider.th.* table headers.
"""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')

T = {
    'es': {
        'title': 'Flujo en Tiempo Real · Actividad Interna',
        'subtitle': 'SEC Form 4 + 13D/13G + flujo de opciones + institucional coreano — seguimiento de capital en tiempo real nivel Bloomberg',
        'loading': 'Cargando datos...',
        'refresh': 'Actualizar',
        'empty': 'Sin datos',
        'buy': 'Compra', 'sell': 'Venta',
        'tabInsider': 'Operaciones Internas (Form 4)',
        'tabOwnership': 'Participación (13D/G)',
        'tabNport': 'Fondos N-PORT',
        'tabBlocks': 'Operaciones en Bloque',
        'tabOptions': 'Flujo de Opciones',
        'tabKorea': 'Flujo Corea',
        'explainerTitle': 'Bloomberg tampoco ofrece 13F en tiempo real — retraso legal de 45 días',
        'explainerBody': 'Pero combinando Form 4 (D+2) de operaciones internas, Schedule 13D/13G (cruces del 5%+), flujo inusual de opciones y compras netas de extranjeros/instituciones de KRX, obtienes señales institucionales en vivo. Esta página las integra.',
        'koreaAsOf': 'al {date}',
        'tickers': 'tickers',
        'foreignTopBuy': 'Top compras netas extranjeras',
        'foreignTopSell': 'Top ventas netas extranjeras',
        'instTopBuy': 'Top compras netas institucionales',
        'instTopSell': 'Top ventas netas institucionales',
        'sources': 'Fuentes: SEC EDGAR (Form 4, 13D/13G, N-PORT), Polygon.io, Unusual Whales, KRX · caché 5-30 min',
        'nportExplainer': 'Form N-PORT es la divulgación mensual de tenencias de fondos mutuos — 3× más rápido que 13F (trimestral), con retraso de 60 días: ves qué compraron Fidelity / Vanguard / BlackRock el mes pasado.',
        'tickerFilterPlaceholder': 'Filtrar por ticker (ej. NVDA)',
        'clusters': 'Clústeres',
        'th': {
            'filed': 'Registrado', 'ticker': 'Ticker', 'issuer': 'Emisor', 'insider': 'Insider', 'role': 'Rol',
            'action': 'Lado', 'shares': 'Acciones', 'price': 'Precio', 'value': 'Valor',
            'filer': 'Declarante', 'formType': 'Formulario', 'percent': '% Propiedad', 'sharesOwned': 'Acciones Poseídas',
            'time': 'Hora', 'sentiment': 'Sentimiento', 'contract': 'Strike · Vencim.', 'size': 'Tamaño', 'premium': 'Prima',
            'totalValue': 'Valor Total', 'fundCount': 'Nº Fondos', 'topFunds': 'Fondos Top', 'exchange': 'Bolsa',
        },
    },
    'fr': {
        'title': 'Flux en Temps Réel · Activité Interne',
        'subtitle': "SEC Form 4 + 13D/13G + flux d'options + institutionnel coréen — suivi de capitaux en temps réel niveau Bloomberg",
        'loading': 'Chargement...',
        'refresh': 'Actualiser',
        'empty': 'Aucune donnée',
        'buy': 'Achat', 'sell': 'Vente',
        'tabInsider': "Transactions d'initiés (Form 4)",
        'tabOwnership': 'Participation (13D/G)',
        'tabNport': 'Fonds N-PORT',
        'tabBlocks': 'Blocs',
        'tabOptions': "Flux d'options",
        'tabKorea': 'Flux Corée',
        'explainerTitle': "Bloomberg ne peut pas donner le 13F en temps réel non plus — délai légal de 45 jours",
        'explainerBody': "Mais en combinant Form 4 (J+2) transactions d'initiés, Schedule 13D/13G (franchissements de 5%+), flux inhabituel d'options, et achats nets étrangers/institutionnels KRX, on obtient des signaux institutionnels en direct.",
        'koreaAsOf': 'au {date}',
        'tickers': 'tickers',
        'foreignTopBuy': "Top achats nets étrangers",
        'foreignTopSell': 'Top ventes nettes étrangères',
        'instTopBuy': 'Top achats nets institutionnels',
        'instTopSell': 'Top ventes nettes institutionnelles',
        'sources': 'Sources : SEC EDGAR (Form 4, 13D/G, N-PORT), Polygon.io, Unusual Whales, KRX · cache 5-30 min',
        'nportExplainer': "Form N-PORT est la divulgation mensuelle des positions des fonds mutuels — 3× plus rapide que 13F (trimestriel), délai de 60 jours : on voit ce que Fidelity / Vanguard / BlackRock ont acheté le mois dernier.",
        'tickerFilterPlaceholder': 'Filtrer par ticker (ex. NVDA)',
        'clusters': 'Clusters',
        'th': {
            'filed': 'Dépôt', 'ticker': 'Ticker', 'issuer': 'Émetteur', 'insider': 'Initié', 'role': 'Rôle',
            'action': 'Sens', 'shares': 'Actions', 'price': 'Prix', 'value': 'Valeur',
            'filer': 'Déclarant', 'formType': 'Formulaire', 'percent': '% Détenu', 'sharesOwned': 'Actions Détenues',
            'time': 'Heure', 'sentiment': 'Sentiment', 'contract': 'Strike · Échéance', 'size': 'Taille', 'premium': 'Prime',
            'totalValue': 'Valeur Totale', 'fundCount': 'Nb Fonds', 'topFunds': 'Fonds Top', 'exchange': 'Bourse',
        },
    },
    'de': {
        'title': 'Echtzeit-Flow · Insider-Aktivität',
        'subtitle': 'SEC Form 4 + 13D/13G + Options-Flow + koreanische Institutionelle — Bloomberg-Echtzeitverfolgung',
        'loading': 'Daten werden geladen...',
        'refresh': 'Aktualisieren',
        'empty': 'Keine Daten',
        'buy': 'Kauf', 'sell': 'Verkauf',
        'tabInsider': 'Insider-Transaktionen (Form 4)',
        'tabOwnership': 'Beteiligungen (13D/G)',
        'tabNport': 'N-PORT Fonds',
        'tabBlocks': 'Block-Trades',
        'tabOptions': 'Options-Flow',
        'tabKorea': 'Korea-Flow',
        'explainerTitle': 'Bloomberg liefert 13F auch nicht in Echtzeit — 45 Tage gesetzliche Verzögerung',
        'explainerBody': 'Durch Kombination von Form 4 (T+2) Insider-Trades, Schedule 13D/13G (5%-Überschreitung), ungewöhnlichem Options-Flow und KRX-Auslandskäufen/institutionellen Nettokäufen erhält man Echtzeit-Institutionssignale.',
        'koreaAsOf': 'Stand {date}',
        'tickers': 'Tickers',
        'foreignTopBuy': 'Top Netto-Auslandskäufe',
        'foreignTopSell': 'Top Netto-Auslandsverkäufe',
        'instTopBuy': 'Top Netto-Institutionskäufe',
        'instTopSell': 'Top Netto-Institutionsverkäufe',
        'sources': 'Quellen: SEC EDGAR (Form 4, 13D/G, N-PORT), Polygon.io, Unusual Whales, KRX · 5-30 min Cache',
        'nportExplainer': 'Form N-PORT ist die monatliche Bestandsoffenlegung für Investmentfonds — 3× schneller als 13F (vierteljährlich) mit 60 Tagen Verzögerung.',
        'tickerFilterPlaceholder': 'Nach Ticker filtern (z.B. NVDA)',
        'clusters': 'Cluster',
        'th': {
            'filed': 'Eingereicht', 'ticker': 'Ticker', 'issuer': 'Emittent', 'insider': 'Insider', 'role': 'Rolle',
            'action': 'Seite', 'shares': 'Aktien', 'price': 'Preis', 'value': 'Wert',
            'filer': 'Einreicher', 'formType': 'Formular', 'percent': '% Besitz', 'sharesOwned': 'Aktien im Besitz',
            'time': 'Zeit', 'sentiment': 'Sentiment', 'contract': 'Strike · Verfall', 'size': 'Größe', 'premium': 'Prämie',
            'totalValue': 'Gesamtwert', 'fundCount': 'Fonds-Anzahl', 'topFunds': 'Top-Fonds', 'exchange': 'Börse',
        },
    },
    'pt': {
        'title': 'Fluxo em Tempo Real · Atividade Interna',
        'subtitle': 'SEC Form 4 + 13D/13G + fluxo de opções + institucional coreano — rastreamento de capital em tempo real nível Bloomberg',
        'loading': 'Carregando...',
        'refresh': 'Atualizar',
        'empty': 'Sem dados',
        'buy': 'Compra', 'sell': 'Venda',
        'tabInsider': 'Operações de Insiders (Form 4)',
        'tabOwnership': 'Participação (13D/G)',
        'tabNport': 'Fundos N-PORT',
        'tabBlocks': 'Blocos',
        'tabOptions': 'Fluxo de Opções',
        'tabKorea': 'Fluxo Coreia',
        'explainerTitle': 'Bloomberg também não oferece 13F em tempo real — atraso legal de 45 dias',
        'explainerBody': 'Mas combinando Form 4 (D+2), Schedule 13D/13G (5%+), fluxo incomum de opções e compras líquidas estrangeiras/institucionais KRX, obtém-se sinais institucionais ao vivo.',
        'koreaAsOf': 'em {date}',
        'tickers': 'tickers',
        'foreignTopBuy': 'Top compras líquidas estrangeiras',
        'foreignTopSell': 'Top vendas líquidas estrangeiras',
        'instTopBuy': 'Top compras líquidas institucionais',
        'instTopSell': 'Top vendas líquidas institucionais',
        'sources': 'Fontes: SEC EDGAR (Form 4, 13D/G, N-PORT), Polygon.io, Unusual Whales, KRX · cache 5-30 min',
        'nportExplainer': 'Form N-PORT é a divulgação mensal de carteira dos fundos mútuos — 3× mais rápido que 13F (trimestral), com atraso de 60 dias.',
        'tickerFilterPlaceholder': 'Filtrar por ticker (ex. NVDA)',
        'clusters': 'Clusters',
        'th': {
            'filed': 'Registrado', 'ticker': 'Ticker', 'issuer': 'Emissor', 'insider': 'Insider', 'role': 'Função',
            'action': 'Lado', 'shares': 'Ações', 'price': 'Preço', 'value': 'Valor',
            'filer': 'Declarante', 'formType': 'Formulário', 'percent': '% Posse', 'sharesOwned': 'Ações Possuídas',
            'time': 'Hora', 'sentiment': 'Sentimento', 'contract': 'Strike · Venc.', 'size': 'Tamanho', 'premium': 'Prêmio',
            'totalValue': 'Valor Total', 'fundCount': 'Nº Fundos', 'topFunds': 'Top Fundos', 'exchange': 'Bolsa',
        },
    },
    'ru': {
        'title': 'Потоки в Реальном Времени · Инсайдерская Активность',
        'subtitle': 'SEC Form 4 + 13D/13G + поток опционов + корейский институционал — отслеживание капитала уровня Bloomberg',
        'loading': 'Загрузка данных...',
        'refresh': 'Обновить',
        'empty': 'Нет данных',
        'buy': 'Покупка', 'sell': 'Продажа',
        'tabInsider': 'Инсайдерские сделки (Form 4)',
        'tabOwnership': 'Владение (13D/G)',
        'tabNport': 'Фонды N-PORT',
        'tabBlocks': 'Блок-сделки',
        'tabOptions': 'Поток опционов',
        'tabKorea': 'Поток Корея',
        'explainerTitle': 'Bloomberg тоже не даёт 13F в реальном времени — 45-дневная задержка по закону',
        'explainerBody': 'Но комбинируя Form 4 (Д+2), Schedule 13D/13G (пересечение 5%+), необычный поток опционов и чистые покупки иностранных/институциональных KRX — получаем живые институциональные сигналы.',
        'koreaAsOf': 'на {date}',
        'tickers': 'тикеры',
        'foreignTopBuy': 'Топ чистых покупок иностранцев',
        'foreignTopSell': 'Топ чистых продаж иностранцев',
        'instTopBuy': 'Топ чистых покупок институтов',
        'instTopSell': 'Топ чистых продаж институтов',
        'sources': 'Источники: SEC EDGAR, Polygon.io, Unusual Whales, KRX · кэш 5-30 мин',
        'nportExplainer': 'Form N-PORT — ежемесячное раскрытие портфелей паевых фондов — в 3 раза быстрее 13F (квартал) с задержкой 60 дней.',
        'tickerFilterPlaceholder': 'Фильтр по тикеру (напр. NVDA)',
        'clusters': 'Кластеры',
        'th': {
            'filed': 'Подано', 'ticker': 'Тикер', 'issuer': 'Эмитент', 'insider': 'Инсайдер', 'role': 'Роль',
            'action': 'Сторона', 'shares': 'Акции', 'price': 'Цена', 'value': 'Сумма',
            'filer': 'Заявитель', 'formType': 'Форма', 'percent': '% Владения', 'sharesOwned': 'Владеет акций',
            'time': 'Время', 'sentiment': 'Настроение', 'contract': 'Strike · Экспирация', 'size': 'Размер', 'premium': 'Премия',
            'totalValue': 'Общая стоим.', 'fundCount': 'Кол-во фондов', 'topFunds': 'Топ фондов', 'exchange': 'Биржа',
        },
    },
    'ar': {
        'title': 'التدفق الفوري · نشاط المطلعين',
        'subtitle': 'SEC Form 4 + 13D/13G + تدفق الخيارات + المؤسسات الكورية — تتبع رأس المال الفوري بمستوى Bloomberg',
        'loading': 'جاري التحميل...',
        'refresh': 'تحديث',
        'empty': 'لا بيانات',
        'buy': 'شراء', 'sell': 'بيع',
        'tabInsider': 'صفقات المطلعين (Form 4)',
        'tabOwnership': 'الملكية (13D/G)',
        'tabNport': 'صناديق N-PORT',
        'tabBlocks': 'صفقات الكتلة',
        'tabOptions': 'تدفق الخيارات',
        'tabKorea': 'تدفق كوريا',
        'explainerTitle': 'Bloomberg لا يقدم 13F فوريا أيضا — 45 يوم تأخير قانوني',
        'explainerBody': 'لكن بدمج Form 4 (يوم+2)، Schedule 13D/13G (عبور 5%)، تدفق الخيارات غير المعتاد وصافي مشتريات الأجانب/المؤسسات KRX — نحصل على إشارات مؤسسية مباشرة.',
        'koreaAsOf': 'في {date}',
        'tickers': 'رموز',
        'foreignTopBuy': 'أعلى صافي شراء أجنبي',
        'foreignTopSell': 'أعلى صافي بيع أجنبي',
        'instTopBuy': 'أعلى صافي شراء مؤسسي',
        'instTopSell': 'أعلى صافي بيع مؤسسي',
        'sources': 'المصادر: SEC EDGAR, Polygon.io, Unusual Whales, KRX · تخزين مؤقت 5-30 دقيقة',
        'nportExplainer': 'Form N-PORT هو الإفصاح الشهري عن محافظ صناديق الاستثمار — 3× أسرع من 13F (ربع سنوي) بتأخير 60 يوما.',
        'tickerFilterPlaceholder': 'تصفية بالرمز (مثل NVDA)',
        'clusters': 'مجموعات',
        'th': {
            'filed': 'تم الإيداع', 'ticker': 'الرمز', 'issuer': 'المصدر', 'insider': 'مطلع', 'role': 'الدور',
            'action': 'الجانب', 'shares': 'الأسهم', 'price': 'السعر', 'value': 'القيمة',
            'filer': 'المودع', 'formType': 'النموذج', 'percent': '% الملكية', 'sharesOwned': 'أسهم مملوكة',
            'time': 'الوقت', 'sentiment': 'الاتجاه', 'contract': 'Strike · الانتهاء', 'size': 'الحجم', 'premium': 'العلاوة',
            'totalValue': 'إجمالي القيمة', 'fundCount': 'عدد الصناديق', 'topFunds': 'أفضل الصناديق', 'exchange': 'البورصة',
        },
    },
    'hi': {
        'title': 'रियल-टाइम फ्लो · इनसाइडर गतिविधि',
        'subtitle': 'SEC Form 4 + 13D/13G + ऑप्शन फ्लो + कोरियाई संस्थागत — Bloomberg-स्तर रियल-टाइम कैपिटल ट्रैकिंग',
        'loading': 'डेटा लोड हो रहा है...',
        'refresh': 'रिफ्रेश',
        'empty': 'कोई डेटा नहीं',
        'buy': 'खरीद', 'sell': 'बिक्री',
        'tabInsider': 'इनसाइडर लेनदेन (Form 4)',
        'tabOwnership': 'स्वामित्व (13D/G)',
        'tabNport': 'N-PORT फंड',
        'tabBlocks': 'ब्लॉक ट्रेड',
        'tabOptions': 'ऑप्शन फ्लो',
        'tabKorea': 'कोरिया फ्लो',
        'explainerTitle': 'Bloomberg भी रियल-टाइम 13F नहीं दे सकता — 45-दिन कानूनी देरी',
        'explainerBody': 'लेकिन Form 4 (D+2), Schedule 13D/13G (5%+ क्रॉसिंग), ऑप्शन असामान्य फ्लो और KRX विदेशी/संस्थागत शुद्ध खरीद को मिलाकर लाइव संस्थागत संकेत मिलते हैं।',
        'koreaAsOf': '{date} तक',
        'tickers': 'टिकर',
        'foreignTopBuy': 'शीर्ष विदेशी शुद्ध खरीद',
        'foreignTopSell': 'शीर्ष विदेशी शुद्ध बिक्री',
        'instTopBuy': 'शीर्ष संस्थागत शुद्ध खरीद',
        'instTopSell': 'शीर्ष संस्थागत शुद्ध बिक्री',
        'sources': 'स्रोत: SEC EDGAR, Polygon.io, Unusual Whales, KRX · 5-30 मिनट कैश',
        'nportExplainer': 'Form N-PORT म्यूचुअल फंड के मासिक होल्डिंग्स का खुलासा है — 13F (तिमाही) से 3× तेज़, 60-दिन देरी।',
        'tickerFilterPlaceholder': 'टिकर द्वारा फ़िल्टर (जैसे NVDA)',
        'clusters': 'क्लस्टर',
        'th': {
            'filed': 'फाइल', 'ticker': 'टिकर', 'issuer': 'जारीकर्ता', 'insider': 'इनसाइडर', 'role': 'भूमिका',
            'action': 'दिशा', 'shares': 'शेयर', 'price': 'कीमत', 'value': 'मूल्य',
            'filer': 'दाखिल करने वाला', 'formType': 'फॉर्म', 'percent': '% स्वामित्व', 'sharesOwned': 'शेयर धारित',
            'time': 'समय', 'sentiment': 'भावना', 'contract': 'Strike · समाप्ति', 'size': 'आकार', 'premium': 'प्रीमियम',
            'totalValue': 'कुल मूल्य', 'fundCount': 'फंड संख्या', 'topFunds': 'शीर्ष फंड', 'exchange': 'एक्सचेंज',
        },
    },
    'id': {
        'title': 'Aliran Real-time · Aktivitas Insider',
        'subtitle': 'SEC Form 4 + 13D/13G + aliran opsi + institusional Korea — pelacakan modal real-time tingkat Bloomberg',
        'loading': 'Memuat data...',
        'refresh': 'Segarkan',
        'empty': 'Tidak ada data',
        'buy': 'Beli', 'sell': 'Jual',
        'tabInsider': 'Transaksi Insider (Form 4)',
        'tabOwnership': 'Kepemilikan (13D/G)',
        'tabNport': 'Dana N-PORT',
        'tabBlocks': 'Blok',
        'tabOptions': 'Aliran Opsi',
        'tabKorea': 'Aliran Korea',
        'explainerTitle': 'Bloomberg juga tidak bisa real-time 13F — penundaan hukum 45 hari',
        'explainerBody': 'Tapi menggabungkan Form 4 (H+2), Schedule 13D/13G (5%+), aliran opsi tidak biasa, dan pembelian bersih asing/institusi KRX — mendapat sinyal institusional langsung.',
        'koreaAsOf': 'per {date}',
        'tickers': 'ticker',
        'foreignTopBuy': 'Pembelian bersih asing teratas',
        'foreignTopSell': 'Penjualan bersih asing teratas',
        'instTopBuy': 'Pembelian bersih institusional teratas',
        'instTopSell': 'Penjualan bersih institusional teratas',
        'sources': 'Sumber: SEC EDGAR, Polygon.io, Unusual Whales, KRX · cache 5-30 menit',
        'nportExplainer': 'Form N-PORT adalah pengungkapan kepemilikan bulanan reksa dana — 3× lebih cepat dari 13F (triwulanan), tertunda 60 hari.',
        'tickerFilterPlaceholder': 'Filter berdasarkan ticker (mis. NVDA)',
        'clusters': 'Kluster',
        'th': {
            'filed': 'Diajukan', 'ticker': 'Ticker', 'issuer': 'Penerbit', 'insider': 'Insider', 'role': 'Peran',
            'action': 'Sisi', 'shares': 'Saham', 'price': 'Harga', 'value': 'Nilai',
            'filer': 'Pengaju', 'formType': 'Form', 'percent': '% Kepemilikan', 'sharesOwned': 'Saham Dimiliki',
            'time': 'Waktu', 'sentiment': 'Sentimen', 'contract': 'Strike · Kadaluarsa', 'size': 'Ukuran', 'premium': 'Premi',
            'totalValue': 'Nilai Total', 'fundCount': 'Jumlah Dana', 'topFunds': 'Dana Teratas', 'exchange': 'Bursa',
        },
    },
    'th': {
        'title': 'Flow เรียลไทม์ · กิจกรรมของ Insider',
        'subtitle': 'SEC Form 4 + 13D/13G + options flow + สถาบันเกาหลี — ติดตามเงินทุนเรียลไทม์ระดับ Bloomberg',
        'loading': 'กำลังโหลด...',
        'refresh': 'รีเฟรช',
        'empty': 'ไม่มีข้อมูล',
        'buy': 'ซื้อ', 'sell': 'ขาย',
        'tabInsider': 'ซื้อขาย Insider (Form 4)',
        'tabOwnership': 'การถือหุ้น (13D/G)',
        'tabNport': 'กองทุน N-PORT',
        'tabBlocks': 'Block Trades',
        'tabOptions': 'Options Flow',
        'tabKorea': 'Flow เกาหลี',
        'explainerTitle': 'Bloomberg ก็ให้ 13F เรียลไทม์ไม่ได้ — ล่าช้าทางกฎหมาย 45 วัน',
        'explainerBody': 'แต่การรวม Form 4 (D+2), Schedule 13D/13G (เกิน 5%), options unusual flow และยอดซื้อสุทธิต่างชาติ/สถาบัน KRX จะได้สัญญาณสถาบันแบบสด',
        'koreaAsOf': 'ณ วันที่ {date}',
        'tickers': 'หลักทรัพย์',
        'foreignTopBuy': 'ซื้อสุทธิต่างชาติสูงสุด',
        'foreignTopSell': 'ขายสุทธิต่างชาติสูงสุด',
        'instTopBuy': 'ซื้อสุทธิสถาบันสูงสุด',
        'instTopSell': 'ขายสุทธิสถาบันสูงสุด',
        'sources': 'ที่มา: SEC EDGAR, Polygon.io, Unusual Whales, KRX · แคช 5-30 นาที',
        'nportExplainer': 'Form N-PORT คือการเปิดเผยการถือครองรายเดือนของกองทุนรวม — เร็วกว่า 13F (รายไตรมาส) 3 เท่า ล่าช้า 60 วัน',
        'tickerFilterPlaceholder': 'กรองตาม ticker (เช่น NVDA)',
        'clusters': 'กลุ่ม',
        'th': {
            'filed': 'ยื่นเมื่อ', 'ticker': 'Ticker', 'issuer': 'ผู้ออก', 'insider': 'Insider', 'role': 'ตำแหน่ง',
            'action': 'ทิศทาง', 'shares': 'จำนวนหุ้น', 'price': 'ราคา', 'value': 'มูลค่า',
            'filer': 'ผู้ยื่น', 'formType': 'แบบฟอร์ม', 'percent': '% ถือหุ้น', 'sharesOwned': 'หุ้นที่ถือ',
            'time': 'เวลา', 'sentiment': 'ทิศทาง', 'contract': 'Strike · หมดอายุ', 'size': 'ขนาด', 'premium': 'พรีเมี่ยม',
            'totalValue': 'มูลค่ารวม', 'fundCount': 'จำนวนกองทุน', 'topFunds': 'กองทุนสูงสุด', 'exchange': 'ตลาด',
        },
    },
    'tr': {
        'title': 'Canlı Akış · İçeriden Aktivite',
        'subtitle': 'SEC Form 4 + 13D/13G + opsiyon akışı + Kore kurumsal — Bloomberg seviyesinde canlı sermaye takibi',
        'loading': 'Yükleniyor...',
        'refresh': 'Yenile',
        'empty': 'Veri yok',
        'buy': 'Alış', 'sell': 'Satış',
        'tabInsider': 'İçeriden İşlemler (Form 4)',
        'tabOwnership': 'Ortaklık (13D/G)',
        'tabNport': 'N-PORT Fonlar',
        'tabBlocks': 'Blok İşlemler',
        'tabOptions': 'Opsiyon Akışı',
        'tabKorea': 'Kore Akışı',
        'explainerTitle': "Bloomberg de gerçek zamanlı 13F veremiyor — yasal 45 gün gecikme",
        'explainerBody': 'Ancak Form 4 (G+2), Schedule 13D/13G (%5+ geçiş), olağandışı opsiyon akışı ve KRX yabancı/kurumsal net alımları birleştirilince canlı kurumsal sinyaller elde edilir.',
        'koreaAsOf': '{date} itibarıyla',
        'tickers': 'sembol',
        'foreignTopBuy': 'En çok yabancı net alım',
        'foreignTopSell': 'En çok yabancı net satım',
        'instTopBuy': 'En çok kurumsal net alım',
        'instTopSell': 'En çok kurumsal net satım',
        'sources': 'Kaynaklar: SEC EDGAR, Polygon.io, Unusual Whales, KRX · 5-30 dk önbellek',
        'nportExplainer': "Form N-PORT yatırım fonlarının aylık holding açıklamasıdır — 13F'den (üç aylık) 3× daha hızlı, 60 gün gecikmeli.",
        'tickerFilterPlaceholder': 'Sembolle filtrele (örn. NVDA)',
        'clusters': 'Kümeler',
        'th': {
            'filed': 'Dosyalandı', 'ticker': 'Sembol', 'issuer': 'İhraççı', 'insider': 'İçeriden', 'role': 'Rol',
            'action': 'Yön', 'shares': 'Hisse', 'price': 'Fiyat', 'value': 'Değer',
            'filer': 'Başvuran', 'formType': 'Form', 'percent': '% Sahiplik', 'sharesOwned': 'Sahip Olunan',
            'time': 'Saat', 'sentiment': 'Duyarlılık', 'contract': 'Strike · Vade', 'size': 'Boyut', 'premium': 'Prim',
            'totalValue': 'Toplam Değer', 'fundCount': 'Fon Sayısı', 'topFunds': 'En İyi Fonlar', 'exchange': 'Borsa',
        },
    },
    'vi': {
        'title': 'Dòng Tiền Thời Gian Thực · Hoạt Động Nội Bộ',
        'subtitle': 'SEC Form 4 + 13D/13G + flow quyền chọn + tổ chức Hàn Quốc — theo dõi vốn thời gian thực cấp Bloomberg',
        'loading': 'Đang tải dữ liệu...',
        'refresh': 'Làm mới',
        'empty': 'Không có dữ liệu',
        'buy': 'Mua', 'sell': 'Bán',
        'tabInsider': 'Giao dịch Nội bộ (Form 4)',
        'tabOwnership': 'Sở hữu (13D/G)',
        'tabNport': 'Quỹ N-PORT',
        'tabBlocks': 'Giao dịch Khối',
        'tabOptions': 'Flow Quyền chọn',
        'tabKorea': 'Flow Hàn Quốc',
        'explainerTitle': 'Bloomberg cũng không thể cung cấp 13F thời gian thực — độ trễ pháp lý 45 ngày',
        'explainerBody': 'Nhưng kết hợp Form 4 (D+2), Schedule 13D/13G (vượt 5%), flow quyền chọn bất thường và mua ròng nước ngoài/tổ chức KRX — ta có tín hiệu tổ chức trực tiếp.',
        'koreaAsOf': 'tại {date}',
        'tickers': 'mã',
        'foreignTopBuy': 'Mua ròng nước ngoài hàng đầu',
        'foreignTopSell': 'Bán ròng nước ngoài hàng đầu',
        'instTopBuy': 'Mua ròng tổ chức hàng đầu',
        'instTopSell': 'Bán ròng tổ chức hàng đầu',
        'sources': 'Nguồn: SEC EDGAR, Polygon.io, Unusual Whales, KRX · cache 5-30 phút',
        'nportExplainer': 'Form N-PORT là công bố danh mục hàng tháng của quỹ tương hỗ — nhanh hơn 13F (quý) 3 lần, trễ 60 ngày.',
        'tickerFilterPlaceholder': 'Lọc theo mã (ví dụ NVDA)',
        'clusters': 'Cụm',
        'th': {
            'filed': 'Nộp lúc', 'ticker': 'Mã', 'issuer': 'Tổ chức phát hành', 'insider': 'Nội bộ', 'role': 'Chức vụ',
            'action': 'Hướng', 'shares': 'Cổ phần', 'price': 'Giá', 'value': 'Giá trị',
            'filer': 'Người nộp', 'formType': 'Form', 'percent': '% Sở hữu', 'sharesOwned': 'CP Sở hữu',
            'time': 'Thời gian', 'sentiment': 'Cảm xúc', 'contract': 'Strike · Đáo hạn', 'size': 'Kích thước', 'premium': 'Phí',
            'totalValue': 'Tổng giá trị', 'fundCount': 'Số quỹ', 'topFunds': 'Quỹ hàng đầu', 'exchange': 'Sàn',
        },
    },
}

MESSAGES_DIR = os.path.join(os.path.dirname(__file__), '..', 'messages')
for lang, trans in T.items():
    path = os.path.join(MESSAGES_DIR, f'{lang}.json')
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    ins = data.setdefault('insider', {})
    # Copy all top-level keys except nested 'th'
    for k, v in trans.items():
        if k == 'th':
            continue
        ins[k] = v
    # Merge th headers
    th = ins.setdefault('th', {})
    for hk, hv in trans['th'].items():
        th[hk] = hv
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(f'  {lang}: translated')
print('Done.')
