/**
 * Loader for AI-generated company contexts (macroImpact + rdPipeline).
 * Generated by: scripts/generate-contexts.ts (vLLM locally or Gemini fallback)
 * Updated: weekly via local script → git push → Vercel auto-deploys
 */

import type { MacroImpact, RdPipelineItem } from './companies';

export interface GeneratedContext {
  ticker: string;
  generatedAt: string;
  model: string;
  macroImpact: MacroImpact;
  rdPipeline: RdPipelineItem[];
}

// Dynamic import so build doesn't fail if the file is empty {}
let _cache: Record<string, GeneratedContext> | null = null;

function loadContexts(): Record<string, GeneratedContext> {
  if (_cache) return _cache;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _cache = require('./generated/company-contexts.json') as Record<string, GeneratedContext>;
  } catch {
    _cache = {};
  }
  return _cache!;
}

export function getGeneratedContext(ticker: string): GeneratedContext | null {
  const contexts = loadContexts();
  return contexts[ticker.toUpperCase()] ?? contexts[ticker] ?? null;
}

export function getGeneratedMacroImpact(ticker: string): MacroImpact | null {
  return getGeneratedContext(ticker)?.macroImpact ?? null;
}

export function getGeneratedRdPipeline(ticker: string): RdPipelineItem[] | null {
  const pipeline = getGeneratedContext(ticker)?.rdPipeline;
  return pipeline && pipeline.length > 0 ? pipeline : null;
}

/** Number of companies with generated context */
export function getGeneratedCount(): number {
  return Object.keys(loadContexts()).length;
}
